import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ReduxProvider } from '@/Provider'
import Sidebar from '@/components/Sidebar'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tasklish',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">
      
      <body >
        <ReduxProvider>
            <Navbar/>
            <div className="flex items-start ">
            <Sidebar/>
            {children}
            </div>
        </ReduxProvider>
        </body>
    </html>
  )
}
